language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "justinmarentette11-github"
    token:
      secure: "ehhAbzqanh3JYhvAPRLd4Ga2jciKZoPolk1z0elxArcuOyf+mLRVxFJil02rldj1S5/IrVutzH3Z9jpJhFVF6m1XMtukS0vSNgW/4MAMReeU6sGqWRnKiPCRLS86URlRQxdKeB7Hzdb5BpLqShoZNSwtBY5I2HX+BG+ezRcfSzP3OWS//LoN9Zn0gTvm1pFGBiFGzK7lZD0gNfVDZe/OaXQhmPBJFpGRYtzwyHB5MqxYy0+tnLfpKhoXgoRR6B3efc48MZNeB6wfKroY6HaV3YMnMPoqWY2hmxPJQy0zp3LNF5NEKzGGZ8RU8hzG2r805A9P9f5WrjrxEbjAo4wi0MlkOS8wM2IunYcCeNXFDItACHXy/I1IVkmQeiKMIXyXacbI7XGN+CMmcEGK6lNwXLdkSF7EheJGjAPKUt5O8WZzyRywyJlFi23RPIa/44l4+7w0iOYoNMhje6k5CJBHihdzYi18srd1+og7qmXon4URZcmXMoGuI5tM05QnhAtEGjaPXSKJkg0Ry7bfW9Z3Xy7FS5tzEOLKHbj5TxSo0r68QYFrZTxvEviq+tdmfnLj9vDeqUiAt+U1W1sV6E8IXd4V75p44pJ+pER1zUwemRFcsXExpgEza9MyQ+L/W4TZkCJX9CkdiNYqJEa0zPLbhPjN+fR2gwpf2eXfpWPwNFk="
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'